language: c

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - llvm-3.6
      - llvm-3.6-dev
      - zlib1g-dev
      - libedit-dev
      - g++-4.8
      - clang-3.6

env:
  - LLVM_DIR=/usr/lib/llvm-3.6

script: ./.travis.sh

notifications:
  slack:
    secure: "1bIPQHxpLdpCjjd2Y8IyJqgIEPOhN92FO1lfHtcSH+9p8Z0NmtOyOXpdchisNw8QIzI25lXjj4QZYAHy5Qxn6sx/VG1bGfnFAO5F10Rcngiua2DFw2JOyHDKxn5KDkPaBBmqNTuQeLefJDGA8hCiClY3YvqeKEptEDqFfjiFO/P749divcXlK6HjL5dCs/mnsdl9tM/tujTuNjI6cp2oHtEC5xwNl6NTqlmyxLMBcZNIyCpwtEHMmc2077ci9zARqysZxJfe84kztcTahzqHl3iuY5cdvJ5dMwO9I9/FHOvUR52CWqqMhwftub5z75WqfDzA4dPypLVh28zfSirdNGbg2skN+RSxGqVVvMWFGiR9Yu49oLL4zwflNNPpWxgsVSnEOcrqlAWXT+0nzG52lPRYjzTundq9qqDSKh6DZHZw9KCisGKCpxUIZ0nN7qERjp36tNfGfcbcF8Dlh1/5xEgm2KxPsYLn1RiVYGirPWqW0FlS1dBgQqpwHIFlcCbmHWnPTlgv57Q/GKN3APNmpbPeQ+ExnS86ZF1pZ373n94AyswmiRoKQx8eJlOzZgsoU9Uvah+AbT4wByRiJHJMWtTwA4hamYhGBauasK5HwLmAI0UWfdzKWaRTNZ1J0ha4ieUO/L+jGxGn/LIlruV9Pk8w5D0bC7eWb7sEmkI7IfQ="
